apiVersion: v1
kind: Secret
metadata: {name: minio-secret, namespace: media-pipeline}
type: Opaque
data:
  MINIO_ROOT_USER: bWluaW8=       # "minio"
  MINIO_ROOT_PASSWORD: bWluaW8xMjM0NQ==  # "minio12345"
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: minio, namespace: media-pipeline}
spec:
  replicas: 1
  selector: {matchLabels: {app: minio}}
  template:
    metadata: {labels: {app: minio}}
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-06-13T22-53-53Z
          args: ["server","/data","--console-address",":9001"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom: {secretKeyRef: {name: minio-secret, key: MINIO_ROOT_USER}}
            - name: MINIO_ROOT_PASSWORD
              valueFrom: {secretKeyRef: {name: minio-secret, key: MINIO_ROOT_PASSWORD}}
          ports:
            - {containerPort: 9000}
            - {containerPort: 9001}
---
apiVersion: v1
kind: Service
metadata: {name: minio, namespace: media-pipeline}
spec:
  selector: {app: minio}
  ports:
    - {name: s3, port: 9000, targetPort: 9000}
    - {name: console, port: 9001, targetPort: 9001}
