apiVersion: apps/v1
kind: Deployment
metadata: {name: worker, namespace: media-pipeline}
spec:
  replicas: 2
  selector: {matchLabels: {app: worker}}
  template:
    metadata: {labels: {app: worker}}
    spec:
      containers:
        - name: worker
          image: ghcr.io/example/media-worker:latest # change to your image
          env:
            - {name: DATABASE_URL, value: postgresql+psycopg2://media:media@postgres.media-pipeline.svc.cluster.local:5432/media}
            - {name: REDIS_URL, value: redis://redis.media-pipeline.svc.cluster.local:6379/0}
            - {name: MINIO_ENDPOINT, value: minio.media-pipeline.svc.cluster.local:9000}
            - {name: MINIO_ACCESS_KEY, valueFrom: {secretKeyRef: {name: minio-secret, key: MINIO_ROOT_USER}}}
            - {name: MINIO_SECRET_KEY, valueFrom: {secretKeyRef: {name: minio-secret, key: MINIO_ROOT_PASSWORD}}}
            - {name: MINIO_SECURE, value: "false"}
            - {name: MEDIA_BUCKET, value: media}
            - {name: OUTPUTS_BUCKET, value: outputs}
          command: ["celery","-A","tasks.celery_app","worker","--loglevel=INFO","-Q","celery"]
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: {name: worker-hpa, namespace: media-pipeline}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
